config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'restaurants#index'
  # resources literally creates routes for each controller's method
  resources :restaurants
  resources :cuisines
  resources :comments
  resources :apis
  resources :favorites
  resources :users
  resources :users, only: [:index , :show]
  resources :restaurants_users, only: [:destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :comments
  has_many :restaurant_users , dependent: :destroy
end

app/models/restaurants_user.rb
class RestaurantsUser < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :restaurants
  has_many :comments
  has_many :restaurant_users, dependent: :destroy
end

app/controllers/apis_controller.rb
class ApisController < ApplicationController
  def create
    @new_data = search.parsed_response
    @new_data['restaurants']
    @filtered_response = @new_data['restaurants'].map do |restaurant|
      { 'name' => restaurant['restaurant']['name'],
        'address' => restaurant['restaurant']['location']['address'],
        'img_url' => restaurant['restaurant']['featured_image'],
        'cost' => restaurant['restaurant']['average_cost_for_two'],
        'lat' => restaurant['restaurant']['location']['latitude'],
        'lon' => restaurant['restaurant']['location']['longitude'],
        'restaurant_id' => restaurant['restaurant']['id'],
        'user_rating' => restaurant['restaurant']['user_rating']['aggregate_rating'] }
    end
    render json: @filtered_response
  end

  def new
    params = favorite_params
    params[:user_id] = "#{current_user.id}"
    p @newUser_Restaurant = RestaurantsUser.new(params)
    if @newUser_Restaurant.save
      flash[:notice] = 'Restaurant saved successfully!'
      render json: {'id' => current_user.id}
    else
      flash[:alert] = "failed"
      redirect_back fallback_location: root_path
    end
  end

  # def destory
  #   if @newUser_Restaurant.destory
  #     redirect_to user_path(current_user.id)
  #   else
  #     redirect_to @newUser_Restaurant
  #   end
  # end

  private

  def search
    query = {
      'entity_id' => 280,
      'entity_type' => 'city',
      'cuisines' => cuisine_params['id']
    }
    @cuisine = HTTParty.get('https://developers.zomato.com/api/v2.1/search?', query: query, headers: headers)
  end

  def headers
    header = {
      'user-key' => 'c6dc40392af08897eafe323966c8dcf1'
    }
  end

  def cuisine_params
    id = params.require(:cuisine).permit(:id)
  end

  def favorite_params
    id = params.require(:restaurantsuser).permit(:user_id, :restaurant_id)
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    # @comment = Comment.new
    # @comment.restaurant_id = Restaurant.show.id
  end

  def create
    p
    @comment = Comment.new(comment_params)
    p@comment
    if @comment.save
      redirect_to :back
    else
      # render({ comment: @comment.stream_id })
      redirect_to :back
      # render :new
    end
end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      redirect_to :back
    else
      redirect_to :back
    end
  end

  def comment_params
    params.require(:comment).permit(:author, :content, :user_id, :restaurant_id)
    end
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.new
    @restaurant = User.all
    @cuisines_New = Cuisine.new
  end

  def show
    @new_restaurant = create
    @comment = Comment.new
    @comments = Comment.where(restaurant_id: @new_restaurant.id)
              end

  def create
    # p @restaurant_hash
    #   @restaurant = Restaurant.new(@restaurant_hash)
    #   if @restaurant.save
    #     p @restaurant.id
    #       @id = @restaurant.id
    #       else
    #     p "not saved"
    #    end
    p @restaurant = search.parsed_response
    p @restaurant_hash = { 'name' => @restaurant['name'],
                           'address' => @restaurant['location']['address'],
                           'img_url' => @restaurant['featured_image'],
                           'cost' => @restaurant['average_cost_for_two'],
                           'menu' => @restaurant['menu_url'],
                           'lat' => @restaurant['location']['latitude'],
                           'lon' => @restaurant['location']['longitude'],
                           'restaurant_id' => @restaurant['id'],
                           'user_rating' => @restaurant['user_rating']['aggregate_rating'] }
    Restaurant.find_or_create_by(@restaurant_hash)
  end

  # def destroy
  #   @restaurant = Restaurant.find(params[:id])
  #   if @restaurant.delete
  #     redirect_to user_path(current_user)
  #   else
  #     flash[:alert] = 'Nope you fucked up.'
  #   end
  # end

  private

  # def favorite_params
  #   params.require :restaurant.permit(:name, :address, :img_url, :user_rating)
  # end

  def search
    query = {
      'res_id' => params[:id]
    }
    @search = HTTParty.get('https://developers.zomato.com/api/v2.1/restaurant?', query: query, headers: headers)
  end

  def headers
    header = {
      'user-key' => 'c6dc40392af08897eafe323966c8dcf1'
    }
  end
end

app/controllers/restaurants_users_controller.rb
class RestaurantsUsersController < ApplicationController
    def destroy
       @selected_row = RestaurantsUser.where(user_id: "#{current_user.id}"  , restaurant_id: params[:id] )
      p  row_id  = @selected_row[0].id
         if @selected_row.destroy(row_id)
           redirect_to user_path(current_user.id)
         else
           
         end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @newUser_Restaurant = User.all
  end

  def show
    @newUser_Restaurant = User.find(current_user.id)
    @restaurants = Restaurant.includes(:users).where("users.id=#{current_user.id}").references(:users)
    # @user =
  end

#   def destroy
#
#     p @rest_user = RestaurantsUser.where(user_params)
#     p @rest_user
#
#
#     p @use = User.find(@id[:user_id])
#     p @rest = Restaurant.find(@id[:restaurant_id])
#     p "============================"
#     p @use.restaurants
#     @restaurant = Restaurant.where(:user_id => params[:id])
#     if @restaurant.delete
#       redirect_to user_path
#     else
#       redirect_to :back
#     end
# end

private


def user_params
  @id = params.require(:users).permit(:restaurant_id, :user_id)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comments_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if current_user %>
    <%= f.text_field :author, value: "#{current_user.email}"%>
    <%= f.hidden_field :user_id, value: current_user.id %>

  <% else %>
    <%= f.text_field :author, value: "Anonymous"%>
  <% end %>
  <br>
  <%= f.label :content %>
  <%= f.text_area :content, cols: 80, rows: 15 %>
  <%= f.hidden_field :restaurant_id, value: @new_restaurant.id %>
  <%= f.submit %>

<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
    <div class="flash <%= type %> " >
        <p class="flash-text <%= type %> " >
        <%= message %>
        </p>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Cuisinie</title>
        <%= csrf_meta_tags %>
        <link href="https://fonts.googleapis.com/css?family=Didact+Gothic" rel="stylesheet">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAEI2xahu1c3KN5YYABaD2c6w8aa7sK4J8&libraries=geometry,places">
        </script>
    </head>

    <body>
        <nav role="navigation">
          <a href="/" title="Home"><img id="imglogo" src="http://i.imgur.com/oxokbLO.png"></a>

            <ul>
                <li><%= link_to "Home", restaurants_path %></li>
                <% if current_user %>
                <li>
                  <li> <%= link_to "Favorites", user_path(id: current_user.id) %> </li>
                    
                <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
                </li>
            <% else %>
                <li>
                    <%= link_to "Login",  new_user_session_path %>
                </li>
                <% end %>
            </ul>
        </nav>
        <br><br><br><br><br><br>

        <%= render "layouts/flash" %>
        <div class="theRealPage">
            <%= yield %>
        </div>
    </body>
</html>

app/views/restaurants/_cuisine_search_form.html.erb
<!-- This is the form for selecting the type of food you want to search by. -->
<%= form_for(@cuisines_New, :url =>restaurants_path ) do |f| %>

  <%= f.label :name %>
  <%= f.collection_select(:id,Cuisine.all, :value, :name)%>
  <%= button_tag "Search" , :type=> 'button' ,:class=> 'click'%>

  <% if current_user.present? %>

    <%= f.hidden_field :user_id, :value => current_user.id %>
  <% end %>
<% end %>

app/views/restaurants/index.html.erb
<h1 class="wlcm">Welcome to Cuisinie</h1>
<!-- Main Container -->
<div id="container" class="flexChild columnParent">
	<!-- Container Starts   -->
	<div id="topcolumnParent" class="flexChild columnParent">

		<!--Header -->
		<div id="headerStart" class="flexChild rowParent">

			<div id="logo" class="flexChild">
			</div>

			<div id="header" class="flexChild rowParent">

				<div id="conainerholdingLogo" class="flexChild">
				</div>

				<div id="navBar" class="flexChild selected">
				</div>
			</div>
		</div>

		<!--  Slideshow    -->
		<div id="slideshow" class="flexChild">
			<div>
				<img src="https://b.zmtcdn.com/data/pictures/3/16780333/	dbd5172aeb47f0c0bdc88e4892028cab_featured_v2.jpg" />
			</div>
			<div>
				<img src="http://i.imgur.com/qNzIyqa.jpg" />
			</div>
			<div>
				<img src="http://i.imgur.com/L8Wf4vY.jpg" />
			</div>
			<div>
				<img src="http://i.imgur.com/mxIQMMi.jpg" />
			</div>
			<div>
				<img src="http://i.imgur.com/fXCARJH.jpg" />
			</div>
			<div>
				<img src="http://i.imgur.com/Wk9Z9bO.jpg" />
			</div>
			<div>
				<img src="http://i.imgur.com/wht9Chf.jpg" />
			</div>
		</div>
	</div>

	<!-- Filter and Results    -->


	<div class="theSearchBar">
	<p>Select Your Filters</p>
		<%= render "cuisine_search_form"%>
	</div>
	<div id="bottomColumnParent" class="flexChild columnParent">
		<div id="bottomrowParent" class="flexChild rowParent">
			<!--  Filter  -->
			<div id="filterBar" class="flexChild columnParent">
				<div id="locationFilter" class="flexChild columnParent">
					<div id="cuisineFilter" class="flexChild">
					</div>
					<div id="priceRange" class="flexChild">
					</div>
				</div>
				<!--  Results   -->

				<div id="filteredResults" class="flexChild columnParent">

					<div id="descResults1" class="flexChild"></div>

				</div>
			</div>

			<div id="footer" class="flexChild"></div>
		</div>
	</div>
</div>

app/views/restaurants/show.html.erb
<h1 class="resName">
    <%= @new_restaurant.name %>
</h1>
<h2 class="resAddr">
  <%= @new_restaurant.address%>
</h2>
<div class="lineMeUp">
  <img class="resImg" src="<%= @new_restaurant.img_url %>" alt="img">
  <div id="this">
  </div>
</div>
<div class="commentSection">
  <h4>Comment list:</h4>
  <% @comments.each do |comment| %>
  <tb>
  <p>
    <%= comment.content %>
    <p>Author: <%=User.select(:email).where(id: "#{comment.user_id}")[0].email %></p>
    <% if current_user %>
        <% if current_user.id == comment.user_id%>
        <%= form_for(comment, method: :delete, data: { confirm: "delete?" }) do |f| %>
          <%= f.submit "Delete"%>
           <% end %>
          <% else %>
    <% end %>
    <% end %>
  </p>
  <% end %>
  </tb>
</div>
<div class="costAndFavorite">
  <p> Cost for two: $ <%= @new_restaurant.cost %> <br>
    <% if current_user.present? %>

  Add to favorites:  <%= button_tag "Favorite" , :type=> 'button' ,:class=> 'favorite'%>  <br>
</div>
<div class="leaveAComment">
  <h3>Leave a comment:</h3>
  <%= render "comments/comments_form", comment: @comment %>
  <br>
</div>
<div class="topSecretInformation">
<p class="user_id"><%= current_user.id%></p>
<p class="rest_id"><%= @new_restaurant.id %></p>
</div>
<% end %>
<div class="topSecretInformation">
<p id="lat"><%= @new_restaurant.lat%>
</p>
<p id="lon"><%= @new_restaurant.lon %>
</p>
<p><% @new_restaurant.restaurant_id%>

</div>

app/views/users/_grab_form.html.erb
<%= form_for(@restaurants) do |f| %>
  <% if current_user %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :restaurant_id, value: @restaurants.id %>
    <%= f.submit "Remove" %>
      <% end %>
<% end %>

app/views/users/index.html.erb
<% if current_user.present? %>


<p><%= @user.email %> </p>



<% end %>

app/views/users/show.html.erb
<h1 class="resName">
<%= @newUser_Restaurant.email%>
<% @restaurants.each do |restaurant| %>
<tb>
<p><%= restaurant.name %></p>
<%= restaurant.address %></p>
<img src="<%= restaurant.img_url %>" alt=""></p>
<%= button_to "Remove this restaurant?", restaurants_user_path(restaurant.id), method: :delete, data: {confirm: "Are you sure you want to delete this?"} %>
</tb>
<% end %>